### ISSUE TITLE
features

### ISSUE THREAD

**Issue by mmolaei7878** [MahmoudElbokl/flutter_clean_arch_sample_demo#1]
hi, thank you for this.
the question is we create a feature based on screens or entities?

**Comment by abuzar-rasool** [comment]
In Clean Architecture, features should be created based on entities rather than screens.

Clean Architecture is an architectural pattern that promotes separation of concerns and independence between layers of the application. It emphasizes the importance of defining the domain entities and use cases first, before implementing the user interface or the infrastructure layer.

The entities represent the core of the domain, and they define the business rules and behavior of the application. The use cases represent the actions or operations that can be performed on these entities. The user interface or the infrastructure layer should be designed in a way that they can interact with these entities and use cases.

Creating features based on screens can lead to a tightly coupled and difficult-to-maintain codebase, as changes to the user interface can have ripple effects on the underlying logic. On the other hand, creating features based on entities promotes a modular and scalable architecture, where the user interface or the infrastructure layer can change without affecting the core domain logic.
